23_FormToTemplate/FormToTemplate23_NG/Database06/urls.py
from django.contrib import admin
#from django.urls import path
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    # does not match anything, go to music home page.
    path(r'', include('music.urls')),
    path('music/', include('music.urls')),
]


23_FormToTemplate/FormToTemplate23_NG/music/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
app_name = 'music'
# '$' means end of string. put nothing here.
urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),
    # /music/<album_id>/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

23_FormToTemplate/FormToTemplate23_NG/music/models.py
from django.db import models

# Red pk (primary key) 1
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField (max_length=100)
    album_logo = models.CharField (max_length=1000)

    def __str__ (self):
        return self.album_title + ' - ' + self.artist

class Song (models.Model):
    album = models.ForeignKey (Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)   # mp3, avi, wav, etc.
    song_title = models.CharField(max_length=250)

    def __str__ (self):
        return self.song_title

23_FormToTemplate/FormToTemplate23_NG/music/views.py
#from django.http import Http404
#from django.http import HttpResponse
#from django.template import loader
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index (request):
    all_albums = Album.objects.all()
    return render (request, 'music/index.html', {'all_albums': all_albums })

def detail(request, album_id):
    album = get_object_or_404 (Album, pk=album_id)
    return render (request, 'music/detail.html', {'album': album })

def detail(request, album_id):
    album = get_object_or_404 (Album, pk=album_id)
    try:
        selected_song = album.song_set.get (pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render (request, 'music/detail.html', {
            'album': album,
            'error_message': "You did not select a valid song", 
        })
    else:
        selected_song.si_favorite = True
        selected_song.save()
        return render (request, 'music/detail.html', {'album': album })

23_FormToTemplate/FormToTemplate23_NG/music/templates/music/detail.html
<!--
{{ album }} 
-->
<img src="{{ album.album_logo }}" width="200" height="150">
<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>
{% if error_message %}
    <p><strong>{{ error_message }} </strong><.p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song {{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for = "song{{ forloop.count }}"">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="https://www.dreamstime.com/stock-illustration-golden-star-logo-your-design-vector-illustration-isolated-white-image83940002" width=16 height=16 />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" ="Favorite">
</form>

23_FormToTemplate/FormToTemplate23_NG/music/templates/music/index.html
{% if all_albums %}
    <h3>Here are all my Albums: </h3>
    <ul>
        {% for album in all_albums %} 
            <li><a href="{% url 'music:detail' album.id %}"> {{ album.album_title }}</a></li>  
        {% comment %} 
           <li><a href="/music/{{ album.id }}/"> {{ album.album_title }}</a></li> 
        {% endcomment %}
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any albums</h3>
{% endif %}